### ISSUE TITLE
Tighten up highway shield rules

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-studio-looseleaf.tm2#3]
As part of a discussion about [`ref` formats on ways](http://wiki.openstreetmap.org/wiki/Talk:United_States_roads_tagging#Delaware_State_Roads), I dug up some examples of the regex-based shield rule giving the wrong results:
- [Guatemalan national highways (`CA`)](https://api.tiles.mapbox.com/v4/tristen.gslcjtt9/page.html?access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww#15/13.8650/-89.4723) are treated like California state routes (`CA`).
- At least one [Indian national highway (`NH`)](https://api.tiles.mapbox.com/v4/tristen.gslcjtt9/page.html?access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww#13/13.0275/77.5366) is treated like a New Hampshire state route (`NH`).
- [Texas Farm-to-Market roads (`FM`)](https://api.tiles.mapbox.com/v4/tristen.gslcjtt9/page.html?access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww#16/33.8544/-98.4908) are treated like Micronesian highways (`FM`). They look just like Texas state highways, which can have matching numbers elsewhere in the state. Micronesia doesn’t appear to have any highways matching the regex anyways.

There would be many more examples (such as Cantabria, Spain’s `CA`), but the stylesheet mitigates this issue by only applying shields to motorways and ignoring `ref`s with hyphens.

These issues would be resolved by a) selecting shields based on the `network` tag on route relations (harder – see gravitystorm/openstreetmap-carto#508), or b) somehow limiting the shield rules to a bbox encompassing the U.S. (easier?) and eliminating `FM` from the regex.

**Comment by skylerbunny** [comment]
My vote is for (A). I will admit that in part, this is because I've already completely implemented Wisconsin Interstate, US, and State Highway relations as per the unique network tag syntax, and would be happy to see shield creation based on potentially non unique fields (i.e., anything that is NOT the network field on a route relation) go away so one single solution can be focused on.

This is one of those times where IMHO it's better to be _prescriptive_ ('Do this, and this way, and the code will catch up when it catches up'), rather than attempting to be _descriptive_ of numerous 'approximate ways to render shields', which a current/future map renderer will then have to attempt to muddy through to figure out what it's actually supposed to do with that particular way/relation/ref-on-way combination.

**Comment by ajashton** [comment]
Neither selecting shields based on relations nor limiting the styles to a particular bounding box are possible with CartoCSS given the current vector tiles. Future versions of the vector tiles will address the issue but there is nothing really actionable in this project other than removing the interstate shield styles completely.

**Comment by 1ec5** [comment]
How about removing `FM` from the rule?

**Comment by ajashton** [comment]
Ok, done in f36372a58ef9f91c961ab782e34d77ce57f4e3d2
